[package]
name = "minibar_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minibar = { path = "../lib" }
diesel = { version = "2.1.2", features = ["sqlite"] }
uom = "0.35.0"
