FROM rust:1.72
RUN cargo install cargo-watch

WORKDIR /app
COPY rest/Cargo.lock rest/
COPY rest/Cargo.toml rest/
COPY lib lib/

WORKDIR /app/rest
COPY rest .

RUN cargo build

CMD [ "cargo", "watch", "-s", "echo '[]' | cargo run" ]
